name: docs_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  side_navigation: ^1.0.4
  dropdown_button2: ^2.3.9
  simple_icons: ^7.10.0
  anim_search_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
